# Generated by Django 5.2.10 on 2026-05-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0402_alter_approval_wla_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='regenerate_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mooringonapproval',
            name='site_licensee',
            field=models.BooleanField(default=False),
        ),
    ]
