# Generated by Django 5.2.14 on 2026-06-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0404_alter_proposal_vessel_beam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='regenerate_document_email_notification',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
