# Generated by Django 5.2.15 on 2026-07-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooringlicensing', '0405_approval_regenerate_document_email_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='batch_property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
